### ISSUE TITLE
Image/logo upload is not working

### ISSUE THREAD

**Issue by djzwerg** [backdrop-contrib/webform2pdf#1] opened 2021-09-21 21:05 UTC
After uploading a jpg file this error occurs:

> Argument 1 passed to file_usage_add() must be an instance of File, int given, called in /pathtobackdrop/modules/webform2pdf/includes/webform2pdf.settings.inc on line 1270

A mail will be created but does not contain the PDF (only crypted text). --> new issue https://github.com/backdrop-contrib/webform2pdf/issues/3

**Comment by bugfolder** [comment] 2021-09-21 22:20
Can you be more specific about where you are uploading a .jpg file? From the line number you quoted, it looks like you're saving a logo file in the header or footer. Is that right?

**Comment by bugfolder** [comment] 2021-09-21 23:21
So, I just tried this (uploading a .jpg image to the left side in the PDF header section for a new webform) and encountered no error; it saved properly.

Perhaps check the file permissions in your files directory? The uploaded file should be stored in files/webform2pdf.

Can you add a file component to your test webform and specify that directory as the destination for the component? Then see if submitting the webform with a file component is stored properly.

**Comment by djzwerg** [comment] 2021-09-21 23:28
@bugfolder it's not possible to change the file component's direction from files/webform/ to files/webform2pdf/ because it is hard-coded. The permissions were set to 775 and the files are still there but nothing to see at the pdf file.

**Comment by bugfolder** [comment] 2021-09-21 23:31
So the logo file was uploaded fully? It's in the directory and its thumbnail shows on the Webform2PDF settings page (in the same section where you uploaded it)?

**Comment by djzwerg** [comment] 2021-09-21 23:33
Yes it is in that folder but no its thumbnail won't be shown.

**Comment by djzwerg** [comment] 2021-09-22 00:03
I've tried that again on a clean Backdrop site and the issue is still there. 

- Backdrop: 1.20.0 
- Webform: 1.x-4.24.1
- Webform2pdf: 1.x-4.1.0

**Comment by bugfolder** [comment] 2021-09-22 16:54
One more thing to check (to determine whether it's a problem with mail or with PDF generation).

View one of the submissions and click on the "Download PDF" tab, which should take you to a page like http://example.com/node/4/submission/1/downloadpdf, which should include the logo image. If it's showing up there but not in mail, then it's a mail problem; if it's not showing up there, then it's a problem with the PDF generation.

**Comment by djzwerg** [comment] 2021-09-22 17:20
The PDF doesn't contain the logo. I think the issue occurs between physical file upload and using it within the field.

**Comment by bugfolder** [comment] 2021-09-22 17:37
Yes. This helps to establish, though, because it's easier to debug that part of the chain.

Are you comfortable using the [Devel module](https://backdropcms.org/project/devel) and/or editing PHP to debug? It would be helpful to install and enable Devel, and then insert this line in webform2pdf.settings.inc just before the problematic call to `file_usage_add()`:

```
dpm($file, '$file');
```

It's a puzzle because I can't reproduce this error on my test site.

**Comment by djzwerg** [comment] 2021-09-22 19:44
@bugfolder I've done and this is the result:
![grafik](https://user-images.githubusercontent.com/49948628/134411301-2e9fb54b-217e-452c-bbeb-a6cdcaace0b5.png)

**Comment by djzwerg** [comment] 2021-09-22 20:08
At the Backdrop log:

> Notice: Trying to get property 'fid' of non-object in _webform2pdf_save_logo() (line 1272 von /pathtobackdrop/modules/webform2pdf/includes/webform2pdf.settings.inc).

**Comment by bugfolder** [comment] 2021-09-22 20:11
Yup, I'd expect that based on the debug report you showed. Thanks for that, it helps.

So it looks like (at liine 1267) `file_move()` is returning a status code rather than a file object.

**Comment by djzwerg** [comment] 2021-09-22 20:17
I'm glad that this would help. Looking forward to test code changes :)

**Comment by djzwerg** [comment] 2021-09-22 20:20
While searching for the debug notice I found [that issue](https://www.drupal.org/project/migrate/issues/2266395).
So I thought maybe it would help to change the line 1270 like this:

```
 	  if (is_object($file)) {
		file_usage_add($file, 'webform2pdf', $logo, $nid);
		}
```

I've tried but that doesn't solve this issue. So `file_remove()` maybe causes this.

**Comment by bugfolder** [comment] 2021-09-22 20:42
Hmm. Turns out I have a pending update that addresses that issue that just hadn't been applied yet. (So I've been using the dev version, which is why I'm not seeing the issue, and you are seeing it. D'oh!) Sit tight, let me get these fixes into a new release version and we'll take it up again.

**Comment by bugfolder** [comment] 2021-09-22 20:48
OK, I've pushed a commit that should at least get us seeing consistent things. Would you download the current development version ([from here](https://github.com/backdrop-contrib/webform2pdf), using the green "Code" button) and give it a try?

**Comment by djzwerg** [comment] 2021-09-22 21:24
Great! It works! Thanks a lot!

**Comment by bugfolder** [comment] 2021-09-22 21:25
Great! Bugfix release to follow shortly.

**Comment by djzwerg** [comment] 2021-09-22 21:26
Sorry I have to reopen this issue. Now it is not possible to delete an uploaded image:
![grafik](https://user-images.githubusercontent.com/49948628/134424226-80dec72c-7228-4b85-b19c-afb20831c544.png)

**Comment by djzwerg** [comment] 2021-09-22 21:28
The Backdrop log file show up two messages:

> Warning: array_flip(): Can only flip STRING and INTEGER values! in DefaultEntityController->load() (line 230 of /backdrop/core/modules/entity/entity.controller.inc).

> Recoverable fatal error: Object of class File could not be converted to string in DatabaseStatementBase->execute() (line 2284 of /backdrop/core/includes/database/database.inc).

**Comment by bugfolder** [comment] 2021-09-22 21:29
OK, let me go check it out.

**Comment by bugfolder** [comment] 2021-09-22 21:30
Well, I can reproduce this. (So this gives me something to work on.)

**Comment by bugfolder** [comment] 2022-10-25 02:06
@djzwerg, first, apologies for letting so much time pass — I lost track of this issue being open. Just found it (again). There have been a couple of releases since this issue arose, and just trying out the current version, I'm no longer able to reproduce this issue (uploading a logo file, saving, then trying to delete it). Would you try the latest release and see if you still experience the problem?

**Comment by bugfolder** [comment] 2023-05-17 16:17
Since there was no further response on this, I'm closing the issue. But if it reappears (using the current release version), please do feel free to reopen or post a new issue.

**Closed as completed by bugfolder** 2023-05-17 16:17 UTC
